### PR TITLE
[CP-2274] Fix device connection issue and unresponsive behavior

### PR DESCRIPTION
**Pull request by dkarski**
JIRA Reference: [CP-2274]

### :memo: Description ️

- Reduction of redundantly sent events to the application related to (attached/detached/connected/disconnected).
- Combining two modal views related to connection errors into one.
- Removal of potentially unused code related to handling the device list.
- Improvement of terminology in the code.

### :muscle: Checklist before requesting a review - nice to have

- getState function in async thunk actions is correctly typed
- redux selectors are used in components / prop drilling is reduce

### :exclamation: Checklist before merging a pull request

- change went through the QA process
- translations are updated in dedicated application
- [CHANGELOG.md](./CHANGELOG.md) is updated

[CP-2274]: https://appnroll.atlassian.net/browse/CP-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by OskarMichalkiewicz** [comment]
This changes previous workflow dramatically. Previously we were waiting for some time before showing the error modal. Now it just appears. Previously after closing the modal the app was not listening for connection anymore, now it does and the modal is just showing time and time again.

**Comment by dkarski** [comment]
> This changes previous workflow dramatically. Previously we were waiting for some time before showing the error modal. Now it just appears. Previously after closing the modal the app was not listening for connection anymore, now it does and the modal is just showing time and time again.

Thank you for providing this information ❤️  I greatly appreciate your input on this matter. After consulting with Oskar, I am currently working on improving this pull request, taking into consideration the suggestions that have been raised.

**Comment by dkarski** [comment]
After conducting initial QA tests, I am returning to further enhance the connecting process in a scenario where the user disconnects the device before its connection.

**Comment by dkarski** [comment]
The pull request has been closed due to the high risk of introducing regressions.

**Pull request closed without merging**
