### PR TITLE
Update dependencies vol. 25

### PR DESCRIPTION
**Pull request by igorbezsmertnyi**
Jira: [CP-1492]

**Description**
Update dependencies vol. 25

<details>
<summary><b>Screenshots</b></summary>
// put images here
</details>

[CP-1492]: https://appnroll.atlassian.net/browse/CP-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dkarski — APPROVED** [review]
✅  App works
✅  App (built - mac) works
✅  Storybook works

**Review by wercix — COMMENTED** [review]
Storybook doesn't work :(

**Comment by dkarski** [comment]
> Storybook doesn't work :(

I can't reproduce.
1. Please share the error message
2. What do you have in the browser view after going to http: // localhost: 6006 /

Maybe the above answers will be helped for @igorbezsmertnyi

**Comment by igorbezsmertnyi** [comment]
@wercix 
Fortunately, it works for me too. There are a bunch of errors in the terminal, but those errors were before the update too, and they don't affect the storybook performance.

**Comment by wercix** [comment]
> @wercix Fortunately, it works for me too. There are a bunch of errors in the terminal, but those errors were before the update too, and they don't affect the storybook performance.

After running the command nothing happened, I could not see anything in the browser. I will not insist to block the PR, if it works fine for you.

**Review by wercix — APPROVED** [review]

**Comment by wercix** [comment]
> After running the command nothing happened, I could not see anything in the browser. I will not insist to block the PR, if it works fine for you.

Ok, I checked in one more time, it works fine but only it doesn't opened automatically

**Pull request merged**
